fx_version 'cerulean'
game 'gta5'

author 'Generated by ChatGPT for DannGamers'
description 'Multi License system supporting qs-inventory and ox_lib with exam system (ESX-ready)'
version '1.0.0'

shared_script '@ox_lib/init.lua'

server_scripts {
  '@oxmysql/lib/MySQL.lua',
  'config.lua',
  'server/server.lua',
}

client_scripts {
  'config.lua',
  'client/client.lua',
}

files {
  'locales/en.lua' -- si tienes este archivo, sino quita esta sección
}

lua54 'yes'
