  CREATE TABLE IF NOT EXISTS multi_licenses (
    id INT AUTO_INCREMENT PRIMARY KEY,
    license_type VARCHAR(50) NOT NULL,
    citizen_id VARCHAR(128) NOT NULL,
    issued_by VARCHAR(128) DEFAULT NULL,
    issued_on TIMESTAMP DEFAULT CURRENT_TIMESTAMP
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
